### ISSUE TITLE
Are password hashing functions exposed?

### ISSUE THREAD

**Issue by craigglennie** [FedericoCeratto/nim-libsodium#11]
I'm trying to use `crypto_secretbox_easy`, and I'm getting an error `Error: unhandled exception: len(key) == crypto_secretbox_keybytes()`. I don't know crypto well, but from the libsodium docs I would guess I should be hashing my key with the [password hashing functions](https://download.libsodium.org/doc/password_hashing/) before I pass it to `crypto_secretbox_easy` . But I can't find the password hashing functions in the nim source code? Are they supported, or am I just doing it wrong?

**Comment by enthus1ast** [comment]
for crypto boxes you have to generate a keypair with: 
`let (publicKey, secretKey) = crypto_box_keypair()`

**Comment by FedericoCeratto** [comment]
@craigglennie I added `crypto_secretbox_keygen` and a full example in the documentation.
