### ISSUE TITLE
Expose just the RNG as a wrapped crypto RNG?

### ISSUE THREAD

**Issue by perpetual-hydrofoil** [FedericoCeratto/nim-libsodium#14]
Because the [random module ](https://nim-lang.org/docs/random.html) isn't high enough entropy for crypto, perhaps it might be worth wrapping just the random functions from libsodium and adding to the standard/wrapper library (or perhaps from OpenSSL/LibreSSL) so that other crypto modules have a solid RNG module to depend on.

**Comment by FedericoCeratto** [comment]
If you are suggesting adding part of libsodium to Nim's stdlib the issue should be opened on https://github.com/nim-lang/Nim/issues/
I suspect people would not be happy to add a dependency on libsodium in stdlib, even if it's optional, unfortunately.

**Comment by perpetual-hydrofoil** [comment]
@FedericoCeratto you're probably right; `stdlib` is probably not the right place. Perhaps just another module like `cryptorand` or something. I wonder if the story would be different if `libressl`/`openssl` was the lib in question.

**Comment by jedisct1** [comment]
Since it's a popular request, and some projects are embedding a copy of it already, I'm planning to release minimal, single-file, standalone implementations of libsodium's system and internal RNGs.
