### ISSUE TITLE
`sodium_init` not called and not exposed

### ISSUE THREAD

**Issue by jeromebaum** [FedericoCeratto/nim-libsodium#21]
According to [the libsodium documentation](https://download.libsodium.org/doc/quickstart), `sodium_init` has to be called - and the return value checked - before the library can be safely used. I don't see any reference to `sodium_init` in the codebase. As far as I can see it's not explicitly called, nor is it exposed so that a library user can call it.

This appears to be a critical security issue. The libsodium documentation doesn't specify what happens if you omit the call to `sodium_init` but I would assume it's completely unsafe to use.

**Comment by FedericoCeratto** [comment]
Thank you @jeromebaum for the bug report. I just released 0.6.0 that adds `sodium_init` and calls it automatically.

**Comment by FedericoCeratto** [comment]
The ouputs in the unit and functional tests are not changed by calling `sodium_init` before the run. I suspect the only impact would be on systems affected by the known "low entropy at boot" problem.
Opened https://github.com/jedisct1/libsodium/issues/908 to investigate the impact.
edit: the bug received a reassuring reply. Also searching for `sodium_init` in CVE databases gives no results.
