### ISSUE TITLE
Support crypto_secretstream

### ISSUE THREAD

**Issue by VP8M8** [FedericoCeratto/nim-libsodium#25]
It would be really nice to have support for the crypto_secretstream_*() functions. Being able to easily and securely support stream encryption would be very useful.

A wrapper decryption function like the example at the bottom of https://doc.libsodium.org/secret-key_cryptography/secretstream might be helpful to automatically detect encrypted stream errors.

**Comment by FedericoCeratto** [comment]
Added in 8f0c4555a42979e932984b256fcc8c3b3264de2f
