### ISSUE TITLE
nim-libsodium doesn't support libsodium 26

### ISSUE THREAD

**Issue by Yu-Vitaqua-fer-Chronos** [FedericoCeratto/nim-libsodium#32]
Hi, I've just downloaded libsodium from the arch repos and it seems that the library is outdated, I'm not sure if there are any breaking changes that could impact the library though.

Error: `could not load: libsodium.so(.18|.23)`
Version installed `1.0.19-2` (`libsodium.so.26`)

**Comment by PhilippMDoerner** [comment]
I just did a small local check. The fix is to change
`  const libsodium_fn* = "libsodium.so(.18|.23)`
to
`  const libsodium_fn* = "libsodium.so(.18|.23|.26)"`

in sodium.nim and sodium_sizes.nim.
The test-suite works as normal when run.
