### ISSUE TITLE
Release New version (or patch version?)

### ISSUE THREAD

**Issue by PhilippMDoerner** [FedericoCeratto/nim-libsodium#34]
Heyho!

Just a small request if you could push out a new version of nim-libsodium.
Without the changes from the last PR it basically breaks my test-suite on arch for my nimword package (which uses nim-libsodium to provide hashing for argon in a simple manner).
I could add `requires "libsodium#head"` but I would prefer not to force my users to rely on always the freshest commit :sweat_smile:

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
You could do `requires "libsodium#144d6d8"` (`144d6d8` being the latest commit atm) but a new release would be nice

**Comment by FedericoCeratto** [comment]
Version 0.7.2 released. :)

**Comment by PhilippMDoerner** [comment]
I don't think a new version was actually released. Nimble install libsodium@0.7.2 fails, likely because the current nim version in the nimble file on the master branch remains at 0.7.1
