### ISSUE TITLE
Upgrade to newest libsodium?

### ISSUE THREAD

**Issue by Guppster** [FedericoCeratto/nim-libsodium#5]
This repo depends on libsodium18. Is it possible for you to migrate it to a newer libsodium version?
My package manager only supplies libsodium23... and therefore i cant run the test_sodium file.

**Comment by Guppster** [comment]
Anyway until this is updated, for anyone that runs into this problem you can just do the following:
- Download and extract libsodium-1.0.14 from https://download.libsodium.org/doc/installation/
- Build and install using the directions on the libsodium page
- Copy/link the libraries from ../libsodium-1.0.14/src/libsodium/.libs/ to /usr/lib

**Comment by FedericoCeratto** [comment]
The interface changed between .14 (aka libsodium18) and .15 (aka libsodium23):
https://circleci.com/gh/FedericoCeratto/nim-libsodium/52
I don't want to break backward compatibility given that the older release is the most used. I'll try to support both. PRs are welcome.

**Comment by FedericoCeratto** [comment]
Now both versions are supported.

Tests with the latest version: https://circleci.com/gh/FedericoCeratto/nim-libsodium/54
