### ISSUE TITLE
Statically compile libsodium into executable

### ISSUE THREAD

**Issue by Serasar** [FedericoCeratto/nim-libsodium#7]
Is it possible to compile libsodium stuff inside executable, so it won't depend on libsodium.dll ?

**Comment by FedericoCeratto** [comment]
I'll add instructions based on https://forum.nim-lang.org/t/4034

**Comment by Serasar** [comment]
It seems i managed to compile my exe:
`
--dynlibOverride:libsodium --passL:libsodium.a
`
